
version: '3.8'
services:
      mysql:
        image: mysql:5.7
        container_name: mysql_container
        environment:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: mydb
          MYSQL_USER: user
          MYSQL_PASSWORD: password  
        ports:
          - "3306:3306"
        volumes:
          - mysql_data:/var/lib/mysql
        networks: 
          - my_network
        healthcheck:
            test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
            interval: 30s
            timeout: 10s
            retries: 5
      springboot:
        image: spring-boot:latest
        container_name: springboot_container
        build:
          context: .
          dockerfile: Dockerfile
        ports:
          - "8080:8080"
        depends_on:
          - mysql
        networks: 
          - my_network
        environment:
          MYSQL_URL: jdbc:mysql://mysql:3306/mydb
          MYSQL_USER: user
          MYSQL_PASSWORD: password
        healthcheck:
            test: ["CMD", "curl", "-f", "http://localhost:8080/tickets/all"]
            interval: 30s 
            timeout: 10s
            retries: 5
networks:
  my_network:
    driver: bridge
volumes:
  mysql_data:
    driver: local   

